name: zip
on:
  push:
    tags:
      - "v*.*.*"
env:
  ZIP_NAME: 亚马逊漫画下载器
jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: install zip
        run: |
          sudo apt install zip

      - name: Build zip
        run: |
          find . \( -path ./notes -o -path ./.git -o -path ./README.md -o -path ./.gitignore \) -prune -o -type f -print|xargs zip ${{env.ZIP_NAME}}.zip

      - name: Test zip
        run: |
          zip -sf ${{env.ZIP_NAME}}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{env.ZIP_NAME}}.zip
